# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container at /app
COPY data_pipeline/requirements.txt /app/


# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container at /app
COPY . /app/

# Change permissions to make the script executable
RUN chmod +x data_pipeline/data_processing.sh

# Define environment variable
ENV PYTHONUNBUFFERED=1

RUN ls -R /app/

